server:
    port: 8085
spring:
    datasource:
        password: root
        url: jdbc:mysql://192.168.0.100:3306/shopping_app_product_db?useSSL=false&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&allowPublicKeyRetrieval=true
        username: root
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
#                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: true
