server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: catalogModule
          uri: http://localhost:8081/
          predicates:
            - Path=/catalog/**
        - id: accountsModule
          uri: http://localhost:8082/
          predicates:
            - Path=/accounts/**