server:
    port: 8082
spring:
    datasource:
        password: root
        url: jdbc:mysql://192.168.0.100:3306/shopping_app_accounts_db?allowPublicKeyRetrieval=true&useSSL=false
        username: root
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: true
